const express = require("express");
const router = express.Router();

const authRoutes = require("./AuthRoutes");
const profileRoutes = require("./ProfileRoutes");
const userRoutes = require("./UserRoutes");
const roleRoutes = require("./RoleRoutes");
const permissionRoutes = require("./PermissionRoutes");
const cmsRoutes = require("./CmsRoutes");
const siteSettingRoutes = require("./SiteSettingRoutes");
const faqRoutes = require("./FaqRoutes");
const commonRoutes = require("./CommonRoutes");
const appSettingRoutes = require("./AppSettingRoutes");
const appTranslationRoutes = require("./AppTranslationRoutes");
const contactRoutes = require("./ContactRoutes");
const notificationRoutes = require("./NotificationRoutes");
const societyRoutes = require("./SocietyRoutes");
const societyRoleRoutes = require("./SocietyRoleRoutes");
const societyUserRoutes = require("./SocietyUserRoutes");
const blockRoutes = require("./BlockRoutes");
const towerRoutes = require("./TowerRoutes");
const floorRoutes = require("./FloorRoutes");
const flatRoutes = require("./FlatRoutes");

router.use("/auth", authRoutes);
router.use("/profile", profileRoutes);
router.use("/users", userRoutes);
router.use("/roles", roleRoutes);
router.use("/permissions", permissionRoutes);
router.use("/cms", cmsRoutes);
router.use("/site-settings", siteSettingRoutes);
router.use("/faqs", faqRoutes);
router.use("/common", commonRoutes);
router.use("/app-settings", appSettingRoutes);
router.use("/app-translations", appTranslationRoutes);
router.use("/contacts", contactRoutes);
router.use("/notifications", notificationRoutes);
router.use("/societies", societyRoutes);
router.use("/society-roles", societyRoleRoutes);
router.use("/society-users", societyUserRoutes);
router.use("/blocks", blockRoutes);
router.use("/towers", towerRoutes);
router.use("/floors", floorRoutes);
router.use("/flats", flatRoutes);

module.exports = router;