const express = require('express');
const router = express.Router();

const authRoutes = require('./authRoutes');
const profileRoutes = require('./profileRoutes');
const userRoutes = require('./userRoutes');
const roleRoutes = require('./roleRoutes');
const permissionRoutes = require('./permissionRoutes');
const cmsRoutes = require('./cmsRoutes');
const siteSettingRoutes = require('./siteSettingRoutes');
const faqRoutes = require('./faqRoutes');
const commonRoutes = require('./commonRoutes');
const appSettingRoutes = require('./appSettingRoutes');
const appTranslationRoutes = require('./appTranslationRoutes');
const contactRoutes = require('./ContactRoutes');
const notificationRoutes = require('./NotificationRoutes');
const societyRoutes = require('./SocietyRoutes');
const societyRoleRoutes = require('./SocietyRoleRoutes');
const societyUserRoutes = require('./SocietyUserRoutes');
const blockRoutes = require('./BlockRoutes');
const towerRoutes = require('./TowerRoutes');
const floorRoutes = require('./FloorRoutes');
const flatRoutes = require('./FlatRoutes');

router.use("/auth", authRoutes);
router.use("/profile", profileRoutes);
router.use("/users", userRoutes);
router.use("/roles", roleRoutes);
router.use("/permissions", permissionRoutes);
router.use("/cms", cmsRoutes);
router.use("/site-settings", siteSettingRoutes);
router.use("/faqs", faqRoutes);
router.use("/common", commonRoutes);
router.use("/app-settings", appSettingRoutes);
router.use("/app-translations", appTranslationRoutes);
router.use("/contacts", contactRoutes);
router.use("/notifications", notificationRoutes);
router.use("/societies", societyRoutes);
router.use("/society-roles", societyRoleRoutes);
router.use("/society-users", societyUserRoutes);
router.use("/blocks", blockRoutes);
router.use("/towers", towerRoutes);
router.use("/floors", floorRoutes);
router.use("/flats", flatRoutes);

module.exports = router;
